CVSS_Prediction_API/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from myapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),
]

myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'

urlpatterns = [
    # path(r'', views.index, name='index'),
    path(r'', views.single_decs_query, name='single_decs_query'),
]

myapp/models.py
from django.contrib.auth.models import User
from django.db import models
import datetime


# Create your models here.

class Query(models.Model):
    timestamp = models.DateField(default=datetime.datetime.now)
    output = models.TextField(blank=True)
    input = models.TextField()

    def __str__(self):
        return self.timestamp

myapp/forms.py
from django import forms
from myapp.models import Query


class QueryForm(forms.ModelForm):
    class Meta:
        model = Query
        fields = ['timestamp', 'input']

myapp/views.py
from django.shortcuts import render, redirect

# Import necessary classes
from datetime import *
from .forms import QueryForm
from testing import testing_single_description


# Create your views here.

def single_decs_query(request):
    if request.method == 'POST':
        form = QueryForm(request.POST)
        if form.is_valid():
            input_description = form.cleaned_data['input']
            form.save(commit=False)
            output = testing_single_description(input_description)
            return render(request, 'myapp/single_decs_query.html',
                          {'output': output, 'input': input_description, 'form': form})
        else:
            return render(request, 'myapp/single_decs_query.html', {'form': form})
    else:
        form = QueryForm()
        return render(request, 'myapp/single_decs_query.html', {'form': form})

# def index(request):
#     if request.session.get('last_login'):
#         last_login = request.session['last_login']
#     else:
#         last_login = "Your last login was more than one hour ago"
#     top_list = Topic.objects.all().order_by('id')[:10]
#     return render(request, 'myapp/index.html', {'top_list': top_list, 'last_login': last_login})

myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <title>{% block title %}Single Decs Test{% endblock %}</title>
</head>
<body>
<div class="text-center">
    {% if notif %}
        <h3>{{ notif }}</h3>
    {% endif %}
    <hr/>
    <div class="row">
        {% block body_block %}{% endblock %}
    </div>
</div>
<hr/>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-3"><a href="{% url 'myapp:single_decs_query' %}">Single Decs Test</a></div>
    </div>
</div>
</body>
</html>

myapp/templates/myapp/single_decs_query.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <div class="col-6">
        <form action="{% url 'myapp:single_decs_query' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" name="submit1" value="predict"/>
        </form>
    </div>
    <div class="col-6">
        {% if input %}
            <h3>Input:</h3>
            <p>{{ input }}</p>
        {% else %}
            <strong>There are no Input!</strong>
        {% endif %}
        {% if output %}
            <h3>Output:</h3>
            <p>{{ output }}</p>
        {% else %}
            <strong>There are no output!</strong>
        {% endif %}
    </div>
{% endblock %}